name: Secure CI for Node Backend

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Static Code Analysis - Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"
        continue-on-error: false

      - name: Build Docker Image
        run: docker build -t secure-node-app:latest .

      - name: Container Image Scan - Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'secure-node-app:latest'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true

      - name: DockerHub Login
        if: success()
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Push Secure Image to DockerHub
        if: success()
        run: |
          docker tag secure-node-app:latest yourdockerid/secure-node-app:latest
          docker push yourdockerid/secure-node-app:latest
